language: java
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
jdk:
  - oraclejdk7
  - oraclejdk8

install: /bin/true
script:
  - ./gradlew pathfinding:check -PossrhUsername -PossrhPassword
  - ./gradlew gdx-bridge:check -PossrhUsername -PossrhPassword